SELECT DISTINCT NOMBRE_USUARIO FROM COMPARTIDOS;

SELECT * 
FROM COMPARTIDOS COMP, COMPRA C
WHERE COMP.PROMOCION_ID = C.PROMOCION_ID AND COMP.CODIGO_VALE = C.CODIGO_VALE;

las promociones que fueron compartidas:
CODIGO_VALE = COMPRA FACTURA

SELECT C.CODIGO_VALE, PROMOCION_ID AS PROM, COMP.NOMBRE_USUARIO AS LOGIN,C.FECHA_DE_COMPRA
FROM COMPARTIDOS COMP, COMPRA C
WHERE COMP.CODIGO_VALE = C.CODIGO_VALE
ORDER BY C.FECHA_DE_COMPRA;

SELECT *
FROM COMPRA C1
WHERE (C1.PROMOCION_ID,C1.LOGIN) IN (
	SELECT PROMOCION_ID AS PROM, COMP.NOMBRE_USUARIO AS LOGIN
	FROM COMPARTIDOS COMP, COMPRA C
	WHERE COMP.CODIGO_VALE = C.CODIGO_VALE AND C.FECHA_DE_COMPRA < C1.FECHA_DE_COMPRA)
ORDER BY C1.FECHA_DE_COMPRA;

/******
COMSULTA1: USUARIOS QUE COMPRARON PROMOCIONES QUE LES FUERON COMPARTIDAS
*******/
SELECT C1.LOGIN
FROM COMPRA C1
WHERE (C1.PROMOCION_ID,C1.LOGIN) IN (
	SELECT PROMOCION_ID AS PROM, COMP.NOMBRE_USUARIO AS LOGIN
	FROM COMPARTIDOS COMP, COMPRA C
	WHERE COMP.CODIGO_VALE = C.CODIGO_VALE AND C.FECHA_DE_COMPRA < C1.FECHA_DE_COMPRA)
ORDER BY C1.FECHA_DE_COMPRA;



SELECT C.LOGIN AS QUIEN_COMPARTIO, C1.LOGIN
FROM COMPRA C1, COMPRA C
WHERE (C1.PROMOCION_ID,C1.LOGIN) IN (
	SELECT C.PROMOCION_ID AS PROM, COMP.NOMBRE_USUARIO AS LOGIN
	FROM COMPARTIDOS COMP
	WHERE COMP.CODIGO_VALE = C.CODIGO_VALE AND C.FECHA_DE_COMPRA < C1.FECHA_DE_COMPRA);

	

	
	